# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path_pets": "resnet_pets.ipynb",
         "pat": "resnet_pets.ipynb"}

modules = ["dataset_pets.py"]

doc_url = "https://benymd.github.io/classification/"

git_url = "https://github.com/benymd/classification/tree/master/"

def custom_doc_links(name): return None
